### ISSUE TITLE
Error on Synology NAS DSM 6.2 "No library named udev"

### ISSUE THREAD

**Issue by audiocoach** [0-duke/wdpassport-utils#16]
Trying to setup wdpassport-utils.py on Synology DS411+ii NAS with DSM DSM 6.2.2-24922 Update 4 Installed all the required packages according to the instructions. 

Everything looks good so far, but when I try to use wdpassport-utils.py, I get the following error:

# sudo wdpassport-utils.py
Traceback (most recent call last):
  File "/opt/bin/wdpassport-utils.py", line 457, in <module>
    main(sys.argv[1:])
  File "/opt/bin/wdpassport-utils.py", line 395, in main
    context = pyudev.Context()
  File "/opt/lib/python3.6/site-packages/pyudev/core.py", line 61, in __init__
    self._libudev = load_ctypes_library('udev', SIGNATURES, ERROR_CHECKERS)
  File "/opt/lib/python3.6/site-packages/pyudev/_ctypeslib/utils.py", line 55, in load_ctypes_library
    raise ImportError('No library named %s' % name)
ImportError: No library named udev
Exception ignored in: <bound method Context.__del__ of <pyudev.core.Context object at 0xe1bae8>>
Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/pyudev/core.py", line 65, in __del__
    self._libudev.udev_unref(self)
AttributeError: 'Context' object has no attribute '_libudev'

Any ideas?

**Comment by JoshData** [comment]
>  ImportError: No library named udev

It may be that you don't have libudev. This is a low-level system package so I'm not sure whether this is easily instalable if your system doesn't already have it.

**Comment by 0-duke** [comment]
Closing the issue as this is not related to the tool. As @JoshData pointed out the problem relies on the lack of libraries in your current system.
